export const ALGOLIA_PROVIDER = 'ALGOLIA';
export const CLOUDINARY_PROVIDER = 'CLOUDINARY';
export const FACEBOOK_CLIENT_PROVIDER = 'FACEBOOK_VERIFY';
export const GOOGLE_PROVIDER = 'GOOGLE';
export const TWILIO_VERIFY_PROVIDER = 'TWILIO_VERIFY';
export const TWILIO_MESSAGING_PROVIDER = 'TWILIO_MESSAGING';
export const TWILIO_NOTIFY_PROVIDER = 'TWILIO_NOTIFT_PROVIDER';
export const FIREBASE_PROVIDER = 'FIREBASE';
