import {
  IS_ARRAY,
  IS_BOOLEAN,
  IS_DATE,
  IS_EMAIL,
  IS_ENUM,
  IS_IN,
  IS_INT,
  IS_JWT,
  IS_MOBILE_PHONE,
  IS_NOT_EMPTY,
  IS_NUMBER,
  IS_NUMBER_STRING,
  IS_POSITIVE,
  IS_STRING,
  IS_URL,
  IS_UUID,
  MIN_LENGTH,
} from "class-validator";

export enum ValidationConstraint {
  Exists = "exists",
  IsAllowed = "isAllowed",
  IsArray = IS_ARRAY,
  IsBoolean = IS_BOOLEAN,
  IsDate = IS_DATE,
  IsEmail = IS_EMAIL,
  IsEnum = IS_ENUM,
  IsFile = "isFile",
  IsIn = IS_IN,
  IsInt = IS_INT,
  IsValid = "isValid",
  IsNotExpired = "isNotExpired",
  IsJwt = IS_JWT,
  IsMobilePhone = IS_MOBILE_PHONE,
  IsNumberString = IS_NUMBER_STRING,
  IsNotEmpty = IS_NOT_EMPTY,
  IsNumber = IS_NUMBER,
  IsPositive = IS_POSITIVE,
  IsRegistered = "isRegistered",
  IsNotRegistered = "isNotRegistered",
  IsRequired = "isRequired",
  IsString = IS_STRING,
  IsUUID = IS_UUID,
  IsUrl = IS_URL,
  MinLength = MIN_LENGTH,
}
